/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomCodeRouteImport } from './routes/room.$code'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'
import { Route as ApiPusherWebhooksRouteImport } from './routes/api/pusher/webhooks'
import { Route as ApiPusherAuthRouteImport } from './routes/api/pusher/auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPusherWebhooksRoute = ApiPusherWebhooksRouteImport.update({
  id: '/api/pusher/webhooks',
  path: '/api/pusher/webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPusherAuthRoute = ApiPusherAuthRouteImport.update({
  id: '/api/pusher/auth',
  path: '/api/pusher/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/pusher/webhooks': typeof ApiPusherWebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/pusher/webhooks': typeof ApiPusherWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/room/$code': typeof RoomCodeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/pusher/webhooks': typeof ApiPusherWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/play/$gameId'
    | '/room/$code'
    | '/api/auth/$'
    | '/api/pusher/auth'
    | '/api/pusher/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/play/$gameId'
    | '/room/$code'
    | '/api/auth/$'
    | '/api/pusher/auth'
    | '/api/pusher/webhooks'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/play/$gameId'
    | '/room/$code'
    | '/api/auth/$'
    | '/api/pusher/auth'
    | '/api/pusher/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  RoomCodeRoute: typeof RoomCodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPusherAuthRoute: typeof ApiPusherAuthRoute
  ApiPusherWebhooksRoute: typeof ApiPusherWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pusher/webhooks': {
      id: '/api/pusher/webhooks'
      path: '/api/pusher/webhooks'
      fullPath: '/api/pusher/webhooks'
      preLoaderRoute: typeof ApiPusherWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pusher/auth': {
      id: '/api/pusher/auth'
      path: '/api/pusher/auth'
      fullPath: '/api/pusher/auth'
      preLoaderRoute: typeof ApiPusherAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  RoomCodeRoute: RoomCodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPusherAuthRoute: ApiPusherAuthRoute,
  ApiPusherWebhooksRoute: ApiPusherWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
